### DISCUSSION TITLE
ingress not working after deployment jkube maven

### DISCUSSION THREAD

**Discussion by semanticfire** [eclipse/jkube#1955] [Q&A] [answered]
Due to a downstream update, a project using jkube was deployed by our CI system.

When trying to load the application from the web address, I get a 404 from nginx signaling some wiring is wrong.

If I delete the Ingres from the console, and create it based on the contents of, `target/classes/META-INF/jkube/kubernetes/project-ingress.yml` it starts working immediately.

`src/main/jkube/ingress.yml`
```
apiVersion: networking.k8s.io/v1
metadata:
  name: ${k8sgroupId}-${project.artifactId}-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - ${proj.hostname}
    secretName: letsencrypt-${k8sgroupId}-${project.artifactId}
  rules:
  - host: ${proj.hostname}
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: ${k8sgroupId}-${project.artifactId}-service
              port: 
                number: ${tomee.port}
```

Client Version: v1.25.4
Server Version: v1.21.13-3+cbc10c94808907

Original jkube version was 1.4.0 tried with 1.10.1 but no changes, any hints are greatly appreciated!
