### DISCUSSION TITLE
Discussion regarding `Dapr.io` integration in JKube

### DISCUSSION THREAD

**Discussion by rohanKanojia** [eclipse/jkube#2029] [Ideas]
Related to https://github.com/eclipse/jkube/issues/1996

Schedule a meeting about Dapr.io integration with Eclipse JKube with @vishalrijhwani . @vishalrijhwani would showcase the desired use case so we can understand it better.

@vishalrijhwani Could you please confirm your availability so we can schedule a call to discuss this integration?

**Comment by vishalrijhwani** [comment]
can we have discuss tommorow or day after tommorow or anyday  at 7 pm IST

**Reply by rohanKanojia** [reply]
@manusa @sunix could you please provide your availability?

**Reply by sunix** [reply]
it should work for me

**Reply by manusa** [reply]
Tomorrow won't work.
I'm available Wednesday 2023-02-01 7:00 to 08:30 pm IST (14:30 - 16:00 CET)

**Comment by vishalrijhwani** [comment]
Hi,
        That works for me

Thanks and Regards
Vishal

**Comment by rohanKanojia** [comment]
Shall I schedule a meeting on Wednesday (1st Feb 2023) 7:00 pm - 7:30 pm (IST)?

**Comment by vishalrijhwani** [comment]
Please do it,

Thanks and regards
Vishal

**Comment by rohanKanojia** [comment]
I've created a meeting invite. Could you please accept it if it's okay with your schedule?

**Comment by manusa** [comment]
In case anyone else cares to join the meeting will take place at https://meet.google.com/whb-fzfi-yvw 14:30 CET

**Reply by rohanKanojia** [reply]
@vishalrijhwani : Could you please create a [GitHub project](https://github.com/vishalrijhwani?tab=repositories&type=source) with your project?

**Comment by rohanKanojia** [comment]
As discussed in sync meeting, better solution is to provide annotations in form of a [deployment fragment](https://www.eclipse.org/jkube/docs/kubernetes-gradle-plugin/#kubernetes-resource-fragments):

1. Place this in `src/main/jkube/deployment.yaml`
```yaml
spec:
  template:
    metadata:
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "daprpubsubdemo"
        dapr.io/app-port: "8084"
        dapr.io/config: "appconfig"
        dapr.io/sidecar-liveness-probe-delay-seconds: "2m"
        dapr.io/sidecar-liveness-probe-timeout-seconds: "4m"
        dapr.io/sidecar-readiness-probe-delay-seconds: "2m"
        dapr.io/sidecar-readiness-probe-timeout-seconds: "3m"
```
2. Run `gradle k8Resource`
3. Generated resources should contain these annotations. Eclipse JKube would merge this partial yaml file into finally generated resources
