### DISCUSSION TITLE
Duplicate entries in deployment yaml with gradle plugin

### DISCUSSION THREAD

**Discussion by manojvignesh** [eclipse/jkube#2072] [Q&A] [answered]
I've the below gradle config

```
kubernetes {
    images {
        image {
            name = "..."
        }
    }
    resources {
        namespace = '...'
    }
    enricher {
        config {
            'jkube-prometheus' {
                prometheusPath = '/actuator/prometheus'
                prometheusPort = 8080
            }
            'jkube-healthcheck-spring-boot' {
                failureThreshold = '10'
            }
        }
    }
}

```

with this under `spec.template.spec.containers` I'm getting two entries for same image.
If I remove the images block, it generates only one image entry.

```
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: ...
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 180
          successThreshold: 1
        name: spring-boot
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 9779
          name: prometheus
          protocol: TCP
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          successThreshold: 1
        securityContext:
          privileged: false
      - env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: ...
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 180
          successThreshold: 1
        name: spring-boot
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          successThreshold: 1

```

**Comment by rohanKanojia** [comment, marked as answer]
@manojvignesh : Is your Image configuration complete? I think plugin is trying to create opinionated image itself because it doesn't see full image configuration (requires `build` section where you specify things like `from`, `entrypoint` etc).

Do you just want to configure image name? You can do it using `jkube.generator.name` property.

**Comment by manojvignesh** [comment]
In this case the `images.image.name` was actually ignored. But it inserts a duplicate entry with default name.
If I add `images.image.build.from` along with the above provided one, then it creates only one entry with correct name.
The problem being it doesn't have some ports exposed.

```
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: ...
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 180
          successThreshold: 1
        name: ...
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          successThreshold: 1
        securityContext:
          privileged: false

```

can't I use them both together? images and other configs?
