### DISCUSSION TITLE
How to implement the  nodeSelector spec in my xml configuration

### DISCUSSION THREAD

**Discussion by maodia** [eclipse/jkube#2334] [Q&A] [answered]
Hi, i get a small problem that i am going to deploy my image to some particular k8s node (use nodeSelector spec in the deployment yaml) but i do not know how to configure it in my xml configuration file.  I searched it in the docs and found nothing about this.

**Comment by rohanKanojia** [comment, marked as answer]
I think at the moment it's not provided via XML configuration. I think you should be able to work around this issue by providing a Deployment fragment with nodeSelector.

Place this file in `src/main/jkube` :
`deployment.yaml`
```yaml
spec:
  template:
     spec:
       nodeSelector:
       testkey: testvalue
```
