### DISCUSSION TITLE
Adding Volume

### DISCUSSION THREAD

**Discussion by skumaravelan** [eclipse/jkube#2624] [Q&A] [answered]
I would like to add CSI operator for the deployment, How to apply volume attributes for a deployment. I tried creating a file with .jkube.yaml. Am getting errors. 
] Failed to execute goal org.eclipse.jkube:kubernetes-maven-plugin:1.14.0:resource (default-cli) on project test-stratos: Execution default-cli of goal org.eclipse.jkube:kubernetes-maven-plugin:1.14.0:resource failed: No type given as part of the file name (e.g. 'app-rc.yml') and no 'kind' defined in resource descriptor corp_ca.jkube.yaml.
[ERROR] Must be one of: pr, lr, pv, project, replicaset, cronjob, ds, statefulset, clusterrolebinding, pvc, limitrange, imagestreamtag, networkpolicy, replicationcontroller, is, rb, rc, ingress, route, projectrequest, job, rolebinding, rq, template, serviceaccount, bc, rs, np, persistentvolumeclaim, rbr, role, pod, oauthclient, ns, resourcequota, secret, istag, customerresourcedefinition, sa, persistentvolume, crb, clusterrb, crd, deploymentconfig, configmap, deployment, imagestream, svc, rolebindingrestriction, cj, cm, buildconfig, daemonset, cr, crole, pb, clusterrole, pd, policybinding, service, namespace, dc

```
spec:
  template:
    spec:
      volumes:
        - name: tls
          csi:
            driver: cmcs.crypto-services
            readOnly: true
            volumeAttributes:
              cmcs.crypto-services.com/issuer-name: cm-issuer-corpca
              cmcs.crypto-services.com/issuer-kind: CertificateManagerCorpCA
              cmcs.crypto-services.com/dns-names: localhost
              cmcs.crypto-services.com/key-type: RSA-2048
              cmcs.crypto-services.com/keystore-type: jks
              cmcs.crypto-services.com/key-usages: server
              cmcs.crypto-services.com/common-name: localhost
              # cmcs.crypto-services.com/duration: 2160h
```
