### ISSUE TITLE
Liveness and readiness TCP ports are not serialized as numbers when defined as numbers 

### ISSUE THREAD

**Issue by guiliguili** [eclipse/jkube#1126]
### Description
When specifying liveness and readiness TCP port in `pom.xml` using a number value as follow :

```xml
                        [...]
                        <readiness>
                            <tcpPort>8080</tcpPort>
                        </readiness>
                        <liveness>
                            <tcpPort>8080</tcpPort>
                        </liveness>
                        [...]
```

The generated deployment file is serialized as a string value between double-quotes :

```yml
        [...]
        livenessProbe:
          tcpSocket:
            port: "8080"
        readinessProbe:
          tcpSocket:
            port: "8080"
        [...]
```

### Info

* Eclipse JKube version : 1.5.1
* Maven version (`mvn -v`) : 3.8.3 

### Root cause analysis

The [org.eclipse.jkube.kit.enricher.handler.ProbeHandler#getTCPSocketAction](https://github.com/eclipse/jkube/blob/3455471f7492508ce6ec220642b31d8339e3b8fd/jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/handler/ProbeHandler.java#L105) method is missing a `portObj.setKind(0)` to be compliant with `io.fabric8.kubernetes.api.model.IntOrString.Serializer`
