### ISSUE TITLE
Env vars with KUBERNETES_ name prefix

### ISSUE THREAD

**Issue by lbruun** [eclipse/jkube#1132]
In certain example fragments in the documentation it is shown that you can define your own env var and the name `KUBERNETES_NAMESPACE` is used in the example.

I believe the env var name prefix `KUBERNETES_` is being used by OpenShift ?

I think the documentation **should not encourage a home-made env var with this particular name prefix**. 

It would be better to show example like this:

```yaml
spec:
  ...
  template:
    spec:
      containers:
        - name: my-container
          env:
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
```

which indeed is also the example which the [K8S documentation uses](https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/#use-pod-fields-as-values-for-environment-variables) uses.

The `KUBERNETES_NAMESPACE` is used in some of the examples in the `qiuckstarts` folder as well as in the [AsciiDoc documentation](https://github.com/eclipse/jkube/blob/master/kubernetes-maven-plugin/doc/src/main/asciidoc/inc/_introduction.adoc).
