### ISSUE TITLE
Unable  to set resource request/limit for cpu and memory. 

### ISSUE THREAD

**Issue by jfbourner** [eclipse/jkube#1225]
### Description
When creating the kubenetes.yml I am unable to configure the memory or cpu. I have tried setting it in the src/main /deployment.yml but this is not valid. 

### Info

* Eclipse JKube version : 1.5.1
* Maven version (`mvn -v`) : 3.6.3 
```

```
* Kubernetes version: 1.16.8

* If it's a bug, how to reproduce : Unsure if this is a bug or a feature of the plugin to restrict this. 

* If it's a feature request, what is your use case : I want to limit the CPU and MEM  the container has in the namespace

* Sample Reproducer Project : *[GitHub Clone URL]* n/A (company  repo)

**Comment by rohanKanojia** [comment]
> When creating the kubenetes.yml I am unable to configure the memory or cpu. I have tried setting it in the src/main /deployment.yml but this is not valid.

Do you mean `src/main/jkube/deployment.yml` ?

**Comment by jfbourner** [comment]
Yes I do mean that. My mistake. 
I have updated it with a link to the kubenetes page which gives an example so something like 
`spec:
  containers:
  - name: app
    image: images.my-company.example/app:v4
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"`

**Comment by rohanKanojia** [comment]
I'm not able to reproduce this. Here are the steps I followed:
1. Go to [quickstarts/maven/external-resources](https://github.com/eclipse/jkube/tree/master/quickstarts/maven/external-resources) and update `src/main/jkube/deployment.yml` to this:
```yaml
spec:
  template:
    spec:
      containers:
        - resources:
            limits:
              cpu: "1"
            requests:
              cpu: "0.5"
```
2. Run `mvn k8s:resource -Pkubernetes`
3. Check generated `kubernetes.yml` file in `target`
```
external-resources : $ grep "limits:" -A5 target/classes/META-INF/jkube/kubernetes.yml 
            limits:
              cpu: "1"
            requests:
              cpu: "0.5"
          securityContext:
            privileged: false
```

**Comment by rohanKanojia** [comment]
I think it should work if you modify your fragment like this:
```yaml
spec:
  template:
    spec:
      containers:
        - resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
```
