### ISSUE TITLE
Deprecate / Remove `jkube.io` annotation prefix from JKubeAnnotations 

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#1273]
### Description

While working on https://github.com/eclipse/jkube/issues/1237 , I noticed that we generated some opinionated annotations which are prefixed by `jkube.io`. For example:
```yaml
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      jkube.io/scm-url: https://github.com/spring-projects/spring-boot/random-generator
      jkube.io/git-url: git@github.com:rohanKanojia/eclipse-jkube-demo-project.git
      jkube.io/scm-tag: HEAD
      jkube.io/git-commit: 40b69fc860db02bcbd02dc31e27791b48ccdd4dd
      jkube.io/git-branch: master
```

This reminded me of https://github.com/eclipse/jkube/pull/1245 . This also could be side effect of `s/fabric8/jkube`. Since `jkube.io` is an unreachable address; Does it make sense to replace prefix with something else (`eclipse.org/jkube` or `jkube.eclipse.org`)? It seems to be coming from here:
https://github.com/eclipse/jkube/blob/0957e212de6ce6d9da5dd6aefa6c58d00a8ac853/jkube-kit/config/resource/src/main/java/org/eclipse/jkube/kit/config/resource/JKubeAnnotations.java#L46

I don't think we use these annotations internally as input from users like in the case of #1245 .
