### ISSUE TITLE
Spring Boot actuator endpoints failed to generate automatically if "deployment.yml" resource fragment is used

### ISSUE THREAD

**Issue by simonwg** [eclipse/jkube#1295]
### Info

* Eclipse JKube version : 1.6.0
* Maven version (`mvn -v`) : 3.8.4
```

```
* Kubernetes / Red Hat OpenShift setup and version : OpenShift 3.11

* If it's a bug, how to reproduce : Using the zero-config quickstarts. Add the following in src/main/jkube/deployment.yml

```
spec:
  template:
    spec:
      containers:
        - env:
            - name: ABC
              value: dummy
```
The log will show that "oc: jkube-healthcheck-spring-boot" is not triggered and the output openshift.yml doesn't have readinessProbe and livenessProbe config generated. Same configuration works for JKube 1.5.1

* If it's a feature request, what is your use case :

* Sample Reproducer Project : *[GitHub Clone URL]*
