### ISSUE TITLE
Unwanted container creation in deploymentConfig.yamls due to initContainer

### ISSUE THREAD

**Issue by fscdf** [eclipse/jkube#1316]
### Description

I want to create two docker images in the pom, then run one in an initContainer and one in a normal container. All generated deploymentConfig yaml's contain, however, an additional unwanted container for the second image in the pom.

### Info

The relevant portion of my pom.xml:
```
                    <plugin>
                        <groupId>org.eclipse.jkube</groupId>
                        <artifactId>openshift-maven-plugin</artifactId>
                        <version>1.5.1</version>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>resource</goal>
                                    <goal>apply</goal>
                                    <goal>build</goal>
                                </goals>
                            </execution>
                        </executions>
                        <configuration>
                            <resources>
                                <openshiftBuildConfig>
                                    <requests>
                                        <cpu>1</cpu>
                                        <memory>1Gi</memory>
                                    </requests>
                                    <limits>
                                        <cpu>3</cpu>
                                        <memory>3Gi</memory>
                                    </limits>
                                </openshiftBuildConfig>
                            </resources>
                            <images>
                                <image>
                                    <name>init-image</name>
                                    <alias>init-image-alias</alias>
                                    <build>
                                        <assembly>
                                            <inline>
                                                <files>
                                                    <file>
                                                        <source>
                                                            ${project.basedir}/example_file.txt
                                                        </source>
                                                        <outputDirectory>.</outputDirectory>
                                                    </file>
                                                </files>
                                            </inline>
                                            <name>folder</name>
                                        </assembly>
                                        <from>
                                            some-source:latest
                                        </from>
                                    </build>
                                </image>
                                <image>
                                    <name>backend</name>
                                    <alias>backend-alias</alias>
                                    <build>
                                        <assembly>
                                            <inline>
                                                <files>
                                                    <file>
                                                        <source>
                                                            ${project.basedir}/example_backend_file.txt
                                                        </source>
                                                        <outputDirectory>.</outputDirectory>
                                                    </file>
                                                </files>
                                            </inline>
                                            <name>target_folder</name>
                                        </assembly>
                                        <from>
                                            some-backend-source:latest
                                        </from>
                                    </build>
                                </image>
                            </images>
                        </configuration>
                    </plugin>
```

The initContainer and container are defined as follows.
```
spec:
      initContainers:
        name: init-image
        image: init-image:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 3
            memory: 3Gi
      containers:
        image: backend:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: backend
        resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 3
              memory: 3Gi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
```

In the target/ folder, all generated deploymentConfigs have this container, which shouldn't be there:
```
- env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: backend:latest
        imagePullPolicy: IfNotPresent
        name: backend-alias
        securityContext:
          privileged: false
```

It is important to note, that this unwanted container seems to be a copy of the backend container. This is due to the backend image coming second in the pom. If the order is reversed, the above container will have the init-image.

If, instead of an initContainer and a container, I define two containers in the deployment.yaml, everything works fine.

Not sure if this is a bug or flawed setup.

**Comment by rohanKanojia** [comment]
@fscdf : Thanks for reporting, I can reproduce your issue. From what I see you want to build two images:
- one that would be consumed by `initContainer`
- one that would be main `container`

At the moment, `<images>` only seem to map to `.spec.template.spec.containers[]` field in the generated controller (Deployment, DeploymentConfig etc.)

I think you can work around this issue by separating plugin configuration for building initContainer's image and main container's image. This would take care of building image separately from main application container image. For adding initContainer into DeploymentConfig, you can add a fragment with initContainer details:
```yaml
spec:
  template:
    spec:
      initContainers:
      - name: init-image
        image: init-image:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 3
            memory: 3Gi

```


I've created a demo project, you can see configuration [here](https://github.com/rohankanojia-forks/jkube-testing/blob/main/jkube-initcontainer-fragment/pom.xml#L148)

```
$ mvn oc:build -Pinitcontainer-build # Build InitContainer image
$ mvn oc:build oc:resource oc:apply # Build application
```

However, this would add an extra step for building initContainers image into cluster. It doesn't look good.

I think we need to discuss and add functionality to support initContainers in generated controllers. Or maybe add filters so that some images can only be considered for certain phases (build only, resource only, etc.)
