### ISSUE TITLE
OpenShift route generated targetPort doesn't use the service "normalizePort" 

### ISSUE THREAD

**Issue by simonwg** [eclipse/jkube#1460]
### Description
If "normalizePort" is enabled for service, the generated route's target port doesn't map to the normalized port

### Info

* Eclipse JKube version : 1.7.0
* Maven version (`mvn -v`) : 3.6.4
```

```
* Kubernetes / Red Hat OpenShift setup and version : OpenShift 3.11

* If it's a bug, how to reproduce :

   Enable the `normalizePort` to `true` in maven pom.xml
```
          <configuration>
            <enricher>
              <config>
                <jkube-service>
                  <normalizePort>true</normalizePort>
                </jkube-service>
            </enricher>
          </configuration>
```
   The generated service with port 80 map to target port 8080

```
  kind: Service
  spec:
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
```

   But the route's targetPort still 8080 instead of 80

```
  kind: Route
  spec:
    port:
      targetPort: 8080
```
