### ISSUE TITLE
oc:apply with an image built with jib is not working

### ISSUE THREAD

**Issue by sunix** [eclipse/jkube#1532]
### Description
The openshift deploymentConfig is hanging not starting the pod if `oc:build` has been used with the `jib` strategy.

Workaround: remove from the deploymentConfig
```
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - quarkus
        from:
          kind: ImageStreamTag
          name: jkube-jib-quarkus:latest
      type: ImageChange
```

### Info
* Eclipse JKube version : 1.8.0
* Kubernetes / Red Hat OpenShift setup and version : Devsandbox

#### how to reproduce :

1. create your own quay.io repo empty. mine is `quay.io/sunix/jkube-jib-quarkus`, configure access for jkube to quay.io (see documentation), oc login to an openshift cluster (devsandbox for me)
2. configure `quickstarts/maven/quarkus/pom.xml` with the properties (generator name to be adapted)
     ```
         <jkube.build.strategy>jib</jkube.build.strategy>
         <jkube.generator.name>quay.io/sunix/jkube-jib-quarkus</jkube.generator.name>
     ```
3. run `mvn clean package oc:build oc:push oc:resource oc:apply`
4. everything looks ok but ...
    ![Selection_663](https://user-images.githubusercontent.com/650571/171213397-02ba2777-7a29-4316-a0d0-b5a86bee7761.png)
    in the DeploymentConfig status:
    ```
    status:
      latestVersion: 0
      observedGeneration: 1
      replicas: 0
      updatedReplicas: 0
      availableReplicas: 0
      unavailableReplicas: 0
      conditions:
        - type: Available
          status: 'False'
          lastUpdateTime: '2022-05-31T15:30:52Z'
          lastTransitionTime: '2022-05-31T15:30:52Z'
          message: Deployment config does not have minimum availability.
    ```
