### ISSUE TITLE
DeploymentConfig Resource dropping yml elements for spec.strategy

### ISSUE THREAD

**Issue by pmbsa** [eclipse/jkube#1543]
### Describe the bug

I have a deployment template that has a strategy as follows
```
spec:
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 25%
    type: RollingUpdate
```
after running oc:resource, the result appears to just loose the rollingUpdate: section entirely so the result is 
```
spec:
  strategy:
    type: RollingUpdate
```
I assume I am missing something in my config, has anybody else had this issue at all?

### Eclipse JKube version

1.8.0

### Component

OpenShift Maven Plugin

### Apache Maven version

3.8.3

### Steps to reproduce

1. Have a rollingUpdate strategy define in the deployment template as per the above
2. run mvn oc.resource

### Expected behavior

I expected the resulting DeploymentConfig to have a spec.strategy section like this
```
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 25%
    type: RollingUpdate
```

### Runtime

OpenShift

### Kubernetes API Server version

other (please specify in additional context)

### Environment

Linux

### Additional context

Kubernetes Version: v1.22.8+c02bd9d

**Comment by manusa** [comment]
Your YAML template doesn't seem to adapt to the structure of a DeploymentConfig:

https://docs.openshift.com/container-platform/4.10/rest_api/workloads_apis/deploymentconfig-apps-openshift-io-v1.html#spec-strategy

https://docs.openshift.com/container-platform/4.10/rest_api/workloads_apis/deploymentconfig-apps-openshift-io-v1.html#spec-strategy-rollingparams

I'm not sure, but this seems more like the input you need:
```yaml
spec:
  strategy:
    rollingParams:
      maxSurge: 100%
      maxUnavailable: 25%
    type: Rolling
```
