### ISSUE TITLE
Config Map Enricher appears to be loosing quotes and then corrupting data

### ISSUE THREAD

**Issue by pmbsa** [eclipse/jkube#1647]
### Describe the bug

Hi, I have an example where we have a configmap template with data like this
```
data:
  report_date: "2020-01-01"
```
After the resource action the kubernetes yml has this
```
data:
  report_date: 2020-01-01
```
which then results in a right mess in the deployed CM with the response json showing this
```
"report_date" : "1577836800000"
```
I cant for the life of me understand why the quotes would be dropped but I am hoping its something easy to rectify

### Eclipse JKube version

1.8.0

### Component

Kubernetes Maven Plugin

### Apache Maven version

3.8.3

### Steps to reproduce

1: create a configmap template with the following
```
data:
  report_date: "2020-01-01"
```
run mvn k8s:resource 
the resultant hydrated manifest will be
```
data:
  report_date: 2020-01-01
```

### Expected behavior

should be
```
data:
  report_date: "2020-01-01"
```

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

other (please specify in additional context)

### Environment

Linux

### Additional context

kubernetes 1.19

**Comment by rohanKanojia** [comment]
We seem to be losing quotes since Jackson has been configured:

This setting seems to have been added in https://github.com/eclipse/jkube/pull/1124 
https://github.com/eclipse/jkube/blob/dd105def19fc641a920d3af4b75779caa01212be/jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/ResourceUtil.java#L56

If I comment this setting, I can see quotes retained in generated YAML after `mvn k8s:resource` and also in applied ConfigMap from `mvn k8s:apply` goal

**Comment by rohanKanojia** [comment]
Are you facing issues with losing quotes or date string getting converted into timestamp? I tried configuring Jackson to not convert dates to timestamps:
```
Serialization.jsonMapper().configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false);
```

This results in applied ConfigMap resource like this:
```yaml
data:
  report_date: "2020-01-01T00:00:00.000+00:00"
```
Would this be acceptable for your use case?

**Comment by pmbsa** [comment]
to me it feels like its the quotes going missing is then knocking on the the data being interpreted into nonsense. If the quotes simply remained we would get the date come through as we  want it.

**Comment by manusa** [comment]
As discussed internally, this is a problem of our deserialization process during the Apply phase.

A ConfigMap YAML like the following excerpt:
```yaml
data:
  report_date: 2020-01-01
```

is perfectly valid and should be applied as is to the kube-api server (the same ConfigMap applied with `kubectl` should work). 

Forcing quotes to all string in our serialization process would mitigate this issue partially, but wouldn't tackle the real issue we have with deserialization (which is the one we need to fix). For example, the issue would persist if a user were to provide a fragment with similar unquoted content (which is a valid YAML syntax).

**Comment by msamad** [comment]
Hi, ran into the similar issue with env variables in  `deployment.yaml`, just mentioning here hoping this will be covered in the fix too

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${project.artifactId}
spec:
  selector:
    matchLabels:
      app: ${project.artifactId}
  template:
    metadata:
      labels:
        app: ${project.artifactId}
    spec:
      containers:
        - name: app
          env:
            - name: ENV
              value: local
            - name: SOME_DATE_ENV
              value: '2022-01-01'
          image: ${project.artifactId}:${project.version}
          ports:
            - containerPort: 8080
```
end up as 
```
...
....
      "spec" : {
        "containers" : [ {
          "env" : [ {
            "name" : "ENV",
            "value" : "local"
          }, {
            "name" : "SOME_DATE_ENV",
            "value" : "1640995200000"
          }, {
....
...

```

Thanks

**Comment by manusa** [comment]
> Hi, ran into the similar issue with env variables in `deployment.yaml`, just mentioning here hoping this will be covered in the fix too


Yes, this and other cases where covered in https://github.com/fabric8io/kubernetes-client/pull/4295

The fix should be applied here once we update the Kuberentes Client version with the fix, which will probably be in v1.10.0

Is providing the fragment value as a scalar multi-line a workaround for this issue (it's likely it doesn't work, but it's worth a try)?

```yaml
    spec:
      containers:
        - name: app
          env:
            - name: ENV
              value: local
            - name: SOME_DATE_ENV
              value: >
                2022-01-01
```
