### ISSUE TITLE
Change GitHub Actions permission settings

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#1767]
> Besides the changes from tag to digest, I guess you could start by just adding

```
permissions:  
   contents: read
```

> to your workflows, that would already secure them a lot more.

_Originally posted by @mbarbero in https://github.com/eclipse/jkube/issues/1766#issuecomment-1257857068_

--- 
### Applies to:
- [x] https://github.com/eclipse/jkube
- [x] https://github.com/jkubeio/jkube-integration-tests
- [x] https://github.com/jkubeio/ci

### References
- https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
- https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
- https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
- https://securitylab.github.com/research/github-actions-preventing-pwn-requests/

**Comment by rohanKanojia** [comment]
Besides adding `contents: read`, Do we also need to add this additional step in workflows?

```yaml
      - name: Harden Runner
        uses: step-security/harden-runner@dd2c410b088af7c0dc8046f3ac9a8f4148492a95
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
```

**Comment by rohanKanojia** [comment]
[Harden Runner](https://github.com/step-security/harden-runner) seems to monitor and block outgoing traffic from the GitHub action job.

Initial `egress-policy: audit` monitors all the outgoing requests from GitHub action workflow and generates a report like [this](https://app.stepsecurity.io/github/eclipse/jkube/actions/runs/3901209860):.

The StepSecurity report lists all the outgoing endpoint requests so that we can modify Harden Runner to only allow a specific set of endpoints to be requested:

```yaml
- name: Harden Runner
  uses: step-security/harden-runner@18bf8ad2ca49c14cbb28b91346d626ccfb00c518 # v2.1.0
  with:
    disable-sudo: true
    egress-policy: block
    allowed-endpoints: >
      api.adoptopenjdk.net:443
      github.com:443
      objects.githubusercontent.com:443
      repo.maven.apache.org:443
```

I've created PR https://github.com/eclipse/jkube/pull/1999 to modify `License` and `Quickstart` workflows to use `egress-policy: block`
