### ISSUE TITLE
YAML Multiline block indicator issue 

### ISSUE THREAD

**Issue by jfbourner** [eclipse/jkube#1829]
### Describe the bug

When adding ISTIO configuration, via the annotations config, it is setting a [Block Chomping Indicator](https://yaml.org/spec/1.2.2/#8112-block-chomping-indicator) to clip the new line, where it needs to retain the new line.
[Yaml Multiline](https://yaml-multiline.info/)
[ISTIO Config](https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/)

POM Plugin config 
```
<resources>
	<annotations>
		<all>
			<property>
				<name>proxy.istio.io/config</name>
				<value>proxyMetadata:
    ISTIO_META_DNS_CAPTURE: "false"
holdApplicationUntilProxyStarts: true</value>
			</property>
		</all>
	</annotations>
</resources>
```

Deployment.yml Output 
```  
metadata:
    annotations:
      proxy.istio.io/config: |-
        proxyMetadata:
            ISTIO_META_DNS_CAPTURE: "false"
        holdApplicationUntilProxyStarts: true
```

As you can see above the deployment yaml has "|-" which causes the annotation to not work with ISTIO 

### Eclipse JKube version

1.9.1

### Component

Kubernetes Maven Plugin

### Apache Maven version

3.8.3

### Steps to reproduce

1. Configure the maven plugin - annotation - with multiline text. 
2. Build it using mvn k8s:resource 
3. Check target output

### Expected behavior

Expected output 
```
metadata:
    annotations:
      proxy.istio.io/config:  |
        proxyMetadata:
            ISTIO_META_DNS_CAPTURE: "false"
        holdApplicationUntilProxyStarts: true
```

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

other (please specify in additional context)

### Environment

Windows, Linux

### Sample Reproducer Project

Sits on commercial infra
