### ISSUE TITLE
apiVersion is ignored by resource and apply goals

### ISSUE THREAD

**Issue by tipame** [eclipse/jkube#2219]
### Describe the bug

Hello, in my project i have XML configuration with custom resurce:
```
apiVersion: my.unique.crd/v1alfa1
kind: Template
```
Also i have custom mapping definition:
```
<mapping>
  <kind>Template</kind>
  <filenameTypes>my_template</filenameTypes>
</mapping>
```
As you can see here - there is no way to specify apiVersion in mapping definition - so we have conflict with default Template.
Executing resource goal result to creating ***-template.yaml but not a ***-my_template.yaml (apiVersion property present in generated yaml).
Executing apply goal - ignores ***-template.yaml (no object created in kubernetes).

Executing apply with kubectl work fine (object successfully creates): 
`kubectl apply -f ***-template.yaml`

### Eclipse JKube version

1.13.1

### Component

Kubernetes Maven Plugin

### Apache Maven version

3.8.5

### Gradle version

None

### Steps to reproduce

Create CDR with kind Template (with your unique group):
```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.10.0
  creationTimestamp: null
  name: templates.my.unique.group
spec:
  group: my.unique.group
  names:
    kind: Template
    listKind: TemplateList
    plural: templates
    singular: template
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: TemplateSpec defines the desired state of Template
            properties:
              apiVersion:
                default: v1
                type: string
              data:
                type: string
              kind:
                default: Pod
                type: string
            required:
            - data
            type: object
          status:
            description: TemplateStatus defines the observed state of Template
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      format: date-time
                      type: string
                    message:
                      type: string
                    status:
                      type: string
                    type:
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
              phase:
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
```
Create XML configuration for custom Template:
```
apiVersion: my.unique.group/v1alpha1
kind: Template
metadata:
  name: my-example
  namespace: my-namespace
spec:
data: |-
    spec:    
      containers:
        - name: my-container
```
Add custom mapping definition in pluging configuration:
```
<mappings>
    <mapping>
        <kind>Template</kind>
        <filenameTypes>my_template</filenameTypes>
    </mapping>    
</mappings>
```
k8s:resource produce my-example-template.yaml
k8s:apply ignores my-example-template.yaml (don't know is it right behavior for v1 Template)

### Expected behavior

Expect plugin respect apiVersion and distinguish differend resources with same kind name.
Expect k8s:resource produce my-example-my_template.yaml
Expect k8s:apply successfuly applies my configuration my-example-my_template.yaml (object created in kubernetes).

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.25.3

### Environment

Windows
