### ISSUE TITLE
No Ports exposed inside Deployment in case of Zero Config Dockerfile Mode

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#240]
While modifying integration test PR(https://github.com/jkubeio/jkube-integration-tests/pull/45), I noticed that generated resource manifest seem to be missing ports. Our Enricher API relies only on `ImageConfiguration` field to fetch ports:
https://github.com/eclipse/jkube/blob/07477a232e9ed4d3441622e43fda8f1c9d8466bf/jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/handler/ContainerHandler.java#L164-L170

Here is an example of generated Deployment:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    jkube.io/git-url: git@github.com:jkubeio/jkube-integration-tests.git
    jkube.io/git-commit: abf5c3014bd084a15c59e8b4fd19becf08b2bc0e
    jkube.io/git-branch: pr/simple-dockerfile-test
  labels:
    app: spring-boot-zero-config-dockerfile
    provider: jkube
    version: 0.0.0-SNAPSHOT
    group: org.eclipse.jkube.integration-tests
  name: spring-boot-zero-config-dockerfile
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: spring-boot-zero-config-dockerfile
      provider: jkube
      group: org.eclipse.jkube.integration-tests
  template:
    metadata:
      annotations:
        jkube.io/git-url: git@github.com:jkubeio/jkube-integration-tests.git
        jkube.io/git-commit: abf5c3014bd084a15c59e8b4fd19becf08b2bc0e
        jkube.io/git-branch: pr/simple-dockerfile-test
      labels:
        app: spring-boot-zero-config-dockerfile
        provider: jkube
        version: 0.0.0-SNAPSHOT
        group: org.eclipse.jkube.integration-tests
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: integration-tests/spring-boot-zero-config-dockerfile:latest
        imagePullPolicy: IfNotPresent
        name: integration-tests-spring-boot-zero-config-dockerfile
        securityContext:
          privileged: false
```

As you can see, there is no port being provided inside `.spec.template.spec.containers[0]`. Sadly [DefaultControllerEnricher](https://github.com/eclipse/jkube/blob/master/jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/DefaultControllerEnricher.java#L76) doesn't have any parameter to configure ports:

https://github.com/eclipse/jkube/blob/07477a232e9ed4d3441622e43fda8f1c9d8466bf/jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/DefaultControllerEnricher.java#L76-L83

Maybe we can add an option just like `DefaultServiceEnricher`:
https://github.com/eclipse/jkube/blob/07477a232e9ed4d3441622e43fda8f1c9d8466bf/jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/DefaultServiceEnricher.java#L85-L100
