### ISSUE TITLE
Helm: support for complex values

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#2400]
## Description

Follow up on #2200
Requires #2402 

Be able to provide through Helm values fragments complex values such as annotations or arrays.

```yaml
# values.helm.yaml
annotations:
  example.org/one: one
  example.org/two: two
```

With a fragment such that
```yaml
# deployment.yaml
metadata:
  annotations:
    ${annotations}
```

Can be processed by providing a Helm parameter:

```groovy
// build.gradle
kubernetes {
  helm {
    parameters = [{
      name = 'annotations'
      value = '{{- toYaml .Values.annotations | nindent 4 }}'
    }]
  }
}
```
