### ISSUE TITLE
Cannot use a template variable for `service.yml` on `spec.ports[].port`

### ISSUE THREAD

**Issue by ajeans** [eclipse/jkube#2479]
### Describe the bug

I believe there is a templating problem. Here are the steps, apologies if I failed to read the documentation.

I am trying to push the service port into a template yaml fragment:

File: `src/main/jkube/service-template.yml`
```yaml
kind: Template
parameters:
  - name: service.server.port
    value: 8080
```

While I can use this variable in an ingress fragment...
File: `src/main/jkube/ingress-internal.yml`
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: ${common.namespace}
spec:
  ingressClassName: rfr-internal
  rules:
    - host: ${project.artifactId}.qa1.rfr-tech.net
      http:
        paths:
          - backend:
              service:
                name: ${project.artifactId}
                port:
                  number: ${service.server.port}
            path: /
            pathType: ImplementationSpecific
status:
  loadBalancer:
    ingress:
      - ip: 192.168.212.67
```

... this fails with an error when I try to do the same for the service fragment.

File:`src/main/jkube/service.yml`
```yaml
metadata:
  namespace: ${common.namespace}
spec:
  ports:
    - name: http
      port: ${service.server.port}
      protocol: TCP
      targetPort: http-main
  type: NodePort
```

### Eclipse JKube version

SNAPSHOT

### Component

Kubernetes Maven Plugin

### Apache Maven version

3.8.5

### Gradle version

None

### Steps to reproduce

1. Add all three fragments from the description to a maven project (maybe `quickstarts/maven/spring-boot-helm`)
2. Build the project with
```bash
./mvnw clean install -Dmaven.test.skip
./mvnw k8s:resource k8s:helm
```
3. And notice the error output on the `resource` goal
```log
[ERROR] Failed to execute goal org.eclipse.jkube:kubernetes-maven-plugin:1.16-SNAPSHOT:resource (default-cli) on project microservice-app: Execution default-cli of goal org.eclipse.jkube:kubernetes-maven-plugin:1.16-SNAPSHOT:resource failed: Service null .spec.ports[0].port: required value -> [Help 1]
```

### Expected behavior

Maven generates the k8s resources successfully.

### Runtime

other (please specify in additional context)

### Kubernetes API Server version

1.25.3

### Environment

macOS

### Eclipse JKube Logs

```shell
[INFO] 
[INFO] --- k8s:1.16-SNAPSHOT:resource (default-cli) @ microservice-app ---
[INFO] k8s: Using Dockerfile: /Volumes/Workspace/b2c/template-springboot-microservice/microservice-app/Dockerfile
[INFO] k8s: Using Docker Context Directory: /Volumes/Workspace/b2c/template-springboot-microservice/microservice-app
[INFO] k8s: Using resource templates from /Volumes/Workspace/b2c/template-springboot-microservice/microservice-app/src/main/jkube
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  5.820 s
[INFO] Finished at: 2023-11-27T18:17:39+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.eclipse.jkube:kubernetes-maven-plugin:1.16-SNAPSHOT:resource (default-cli) on project microservice-app: Execution default-cli of goal org.eclipse.jkube:kubernetes-maven-plugin:1.16-SNAPSHOT:resource failed: Service null .spec.ports[0].port: required value -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
```

**Comment by manusa** [comment]
> I am trying to push the service port into a template yaml fragment:

This is no longer the recommended approach, I'd suggest to [configure the parameters](https://eclipse.dev/jkube/docs/kubernetes-maven-plugin/#helm-parameters) using the `pom.xml` file.

For example:
```xml
<plugin>
  <groupId>org.eclipse.jkube</groupId>
  <artifactId>kubernetes-maven-plugin</artifactId>
  <version>${jkube.version}</version>
  <configuration>
    <helm>
      <parameters>
        <parameter>
          <name>ingress.host</name>
          <value>host.example.com</value>
        </parameter>
      </parameters>
    </helm>
  </configuration>
</plugin>
```

Regarding the problem, it's due to the type of the value (I think).
Could you please try something like:
```xml
<plugin>
  <groupId>org.eclipse.jkube</groupId>
  <artifactId>kubernetes-maven-plugin</artifactId>
  <version>${jkube.version}</version>
  <configuration>
    <helm>
      <parameters>
        <parameter>
          <name>service.server.port</name>
          <value>{{ .Values.service.server.port | default 8080 }}</value>
        </parameter>
      </parameters>
    </helm>
  </configuration>
</plugin>
```

**Comment by ajeans** [comment]
> > I am trying to push the service port into a template yaml fragment:
> 
> This is no longer the recommended approach, I'd suggest to [configure the parameters](https://eclipse.dev/jkube/docs/kubernetes-maven-plugin/#helm-parameters) using the `pom.xml` file.
> 
> For example:
> 
> ```
> <plugin>
>   <groupId>org.eclipse.jkube</groupId>
>   <artifactId>kubernetes-maven-plugin</artifactId>
>   <version>${jkube.version}</version>
>   <configuration>
>     <helm>
>       <parameters>
>         <parameter>
>           <name>ingress.host</name>
>           <value>host.example.com</value>
>         </parameter>
>       </parameters>
>     </helm>
>   </configuration>
> </plugin>
> ```
> 
> Regarding the problem, it's due to the type of the value (I think). Could you please try something like:
> 
> ```
> <plugin>
>   <groupId>org.eclipse.jkube</groupId>
>   <artifactId>kubernetes-maven-plugin</artifactId>
>   <version>${jkube.version}</version>
>   <configuration>
>     <helm>
>       <parameters>
>         <parameter>
>           <name>service.server.port</name>
>           <value>{{ .Values.service.server.port | default 8080 }}</value>
>         </parameter>
>       </parameters>
>     </helm>
>   </configuration>
> </plugin>
> ```

* This fails with the same error message. This errors out on the `resources` goal, not the `helm` one, so I assume that the helm configuration change has no effect on this problem.

* Adding a global property in the `pom.xml` file, as you did in the eclipsecon `jkube` branch makes it work for `k8s:resource`, but does not add the value in the `values.yml`of the helm chart.

```xml
    <properties>
        <service.server.port>8080</service.server.port>
    </properties>
```

* Trying to do a go expression inside the property also fails similarly on the `resource` goal

```xml
    <properties>
        <service.server.port>{{ .Values.service.server.port | default 8080 }}</service.server.port>
    </properties>
```

Looking at the source code, it seems to be due to `ServiceDiscoveryEnricher#addAnnotations" when it tries to add the "discovery.3scale.net/port" annotation.

I will try to disable this enricher and see if that helps...

**Comment by ajeans** [comment]
Yes, excluding this enricher seems to make it all work

```diff
                     </images>
+                    <enricher>
+                        <excludes>
+                            <!-- Avoid https://github.com/eclipse/jkube/issues/2479 -->
+                            <exclude>jkube-service-discovery</exclude>
+                        </excludes>
+                    </enricher>
                 </configuration>
             </plugin>
```

With that, I get a working the expected `values.yaml`.

```yaml
[...]
service:
  server:
    port: "8080"
```

Thanks for the youtube link, I know I am focusing on the outer loop, but making the outer loop work fine is my primary goal.
Making `k8s:apply` work too is a nice secondary goal, but worst case, people can use `helm` locally on their k8s clusters.
