### ISSUE TITLE
Well/known and recommended labels breaking existing deployments

### ISSUE THREAD

**Issue by rtroost2012** [eclipse/jkube#2697]
### Describe the bug

Introduced in https://github.com/eclipse/jkube/issues/1700

With a relatively standard JKube configuration, we run into immutability issues after upgrading from v1.15.0 to v1.16.0.

I have limited experience with Kubernetes, but my understanding is that label selectors cannot be changed for existing deployments.

`The Deployment "spring-boot-admin" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app":"spring-boot-admin", "app.kubernetes.io/managed-by":"jkube", "app.kubernetes.io/name":"spring-boot-admin", "app.kubernetes.io/part-of":"nl.aegon.mortgages", "group":"[redacted]", "provider":"jkube"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable`

### Eclipse JKube version

1.16.0

### Component

Kubernetes Maven Plugin

### Apache Maven version

3.8.5

### Gradle version

None

### Steps to reproduce

JKube Configuration
`                    <plugin>
                        <groupId>org.eclipse.jkube</groupId>
                        <artifactId>kubernetes-maven-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>fmp</id>
                                <phase>package</phase>
                                <goals>
                                    <goal>build</goal>
                                    <goal>resource</goal>
                                </goals>
                            </execution>
                        </executions>
                        <configuration>
                            <skip>${kubernetes.skip.generate}</skip>
                            <resourceDir>${kubernetes-fragments-resource-directory}</resourceDir>
                            <imagePullPolicy>Always</imagePullPolicy>
                            <images>
                                <image>
                                    <name>${spring.application.name}:${image.tag}</name>
                                    <alias>${spring.application.name}</alias>
                                    <registry>${image.registry}</registry>
                                    <build>
                                        <from>
                                            [redacted]
                                        </from>
                                        <assembly>
                                            <name>opt</name>
                                        </assembly>
                                        <ports>
                                            <port>8080</port>
                                        </ports>
                                    </build>
                                </image>
                            </images>
                            <resources>
                                <labels>
                                    <all>
                                        <property>
                                            <name>owner</name>
                                            <value>${kubernetes.owner}</value>
                                        </property>
                                    </all>
                                    <service>
                                        <property>
                                            <name>spring-boot</name>
                                            <value>true</value>
                                        </property>
                                    </service>
                                </labels>
                            </resources>
                            <enricher>
                                <config>
                                    <jkube-project-label>
                                        <app>${spring.application.name}</app>
                                    </jkube-project-label>
                                    <jkube-controller>
                                        <name>${spring.application.name}</name>
                                    </jkube-controller>
                                    <jkube-service>
                                        <name>${spring.application.name}</name>
                                        <type>NodePort</type>
                                    </jkube-service>
                                </config>
                                <excludes>
                                    <exclude>jkube-serviceaccount</exclude>
                                </excludes>
                            </enricher>
                        </configuration>
                    </plugin>`

### Expected behavior

Backward-compatibility with old labels or a more explicit warning in the changelog that this might be breaking

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.25.3

### Environment

Amazon

**Comment by rohanKanojia** [comment]
@rtroost2012 : Do you already have Well known Kubernetes labels integrated in your workloads prior to 1.16.0 ?

**Comment by rtroost2012** [comment]
> @rtroost2012 : Did you had Well known Kubernetes labels integrated with your workloads before 1.16.0 ?

Our Kubernetes.yml looks something like this. We have not been using well known labels before 1.16.0


```
---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      jkube.eclipse.org/git-branch: redacted
      jkube.eclipse.org/git-commit: redacted
      jkube.eclipse.org/git-url: redacted
      jkube.eclipse.org/scm-tag: HEAD
      jkube.eclipse.org/scm-url: redacted
    labels:
      app: spring-boot-admin
      group: nl.aegon.mortgages
      owner: ghostbusters
      provider: jkube
      spring-boot: "true"
      version: 0.0.1-SNAPSHOT
....
```

**Comment by rohanKanojia** [comment]
Looking at `field is immutable` error it looks like there is some mismatch between what JKube is trying to apply on Kubernetes cluster and what's already deployed into Kubernetes cluster.

Could you please check what's value has changed in selectors in Deployment ?

**Comment by rtroost2012** [comment]
Adding 

`        <jkube.enricher.jkube-well-known-labels.enabled>false</jkube.enricher.jkube-well-known-labels.enabled>`

To our configuration reverts back to the old behaviour and no immutability issues are encounterd.

The kubernetes YAML after upgrading to 1.16 looks like this

```
---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      jkube.eclipse.org/git-branch: redacted
      jkube.eclipse.org/git-commit: redacted
      jkube.eclipse.org/git-url: redacted
      jkube.eclipse.org/scm-tag: HEAD
      jkube.eclipse.org/scm-url: redacted
    labels:
      app: spring-boot-admin
      app.kubernetes.io/managed-by: jkube
      app.kubernetes.io/name: spring-boot-admin
      app.kubernetes.io/part-of: redacted
      app.kubernetes.io/version: "20240219.880132"
      group: redacted
      owner: ghostbusters
      provider: jkube
      spring-boot: "true"
      version: "20240219.880132"
[...]

    selector:
      app: spring-boot-admin
      app.kubernetes.io/managed-by: jkube
      app.kubernetes.io/name: spring-boot-admin
      app.kubernetes.io/part-of: redacted
      group: redacted
      provider: jkube
```

Previous selector:

```
    selector:
      app: spring-boot-admin
      provider: jkube
      group: redacted
```
