### ISSUE TITLE
OpenShift route generated targetPort doesn't use the service "targetPort"

### ISSUE THREAD

**Issue by luigidemasi** [eclipse/jkube#2847]
### Describe the bug

the generated route's target port doesn't map to the target port, and if the service port is different than target port, so the pod is not accessible through the route.

This is due to https://github.com/eclipse/jkube/issues/1460

For example a fragment like this:
```yaml
metadata:
  annotations:
    api.service.kubernetes.io/path: /services/helloservice/sayHello/
spec:
  ports:
    - port: 80
      targetPort: 8080
```
generate a route like this:

```yaml
apiVersion: route.openshift.io/v1
kind: Route
metadata:

  name: xxxxx
  namespace: xxxxxx
  
spec:
  host: xxxxxxx
  port:
    targetPort: 80
  to:
    kind: Service
    name: xxxxxx
    weight: 100
  wildcardPolicy: None
```

### Eclipse JKube version

1.16.1

### Component

OpenShift Maven Plugin

### Apache Maven version

3.8.5

### Gradle version

None

### Steps to reproduce

create a service fragment with port different than targetPort

### Expected behavior

the generated route in spec.port.targetPort should contains the service targetPort

### Runtime

OpenShift

### Kubernetes API Server version

1.25.3

### Environment

Linux
