### ISSUE TITLE
OpenShift Maven Plugin doesn't add ImageChange triggers when merging from a deployment fragment

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#341]
### Description

Eclipse JKube is not adding ImageChange triggers to `DeploymentConfig` due to which applications deployed in openshift are failing with `ImagePullErr`. This seems to happen in a case when project has some deployment fragment in `src/main/jkube` directory. I have to explicitly add `jkube.openshift.enrichAllWithImageChangeTrigger` property in order to add `ImageChange` triggers:
```
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - spring-boot
        from:
          kind: ImageStreamTag
          name: spring-boot-camel:latest
      type: ImageChange
```

Same project works fine without any extra configuration with Fabric8 Maven Plugin

### Info

* Eclipse JKube version : 1.0.0-rc-1
* Maven version (`mvn -v`) :
```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /opt/apache-maven
Java version: 1.8.0_251, vendor: Oracle Corporation, runtime: /usr/java/jdk1.8.0_251-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.6.19-300.fc32.x86_64", arch: "amd64", family: "unix"
```
* Kubernetes / Red Hat OpenShift setup and version : OpenShift 4.5.1

* If it's a bug, how to reproduce :
- Clone https://github.com/rohanKanojia/spring-boot-camel
- Disable `jkube.openshift.enrichAllWithImageChangeTrigger` property
- deploy application using `mvn clean install -DskipTests oc:deploy -Popenshift`
- application would fail to deploy with `ImagePullErr`

* If it's a feature request, what is your use case :

* Sample Reproducer Project : https://github.com/rohanKanojia/spring-boot-camel
