### ISSUE TITLE
Configuring router in openshift-maven-plugin

### ISSUE THREAD

**Issue by sejacobsen** [eclipse/jkube#356]
### Description
Hi

trying to configure end-to-end encryption for my deployment via the plugin. According to https://docs.openshift.com/container-platform/3.11/architecture/networking/routes.html#route-types I need to configure the router for tls with either rencrypt or passthrough, like the below example:
```
spec:
  port:
    targetPort: https
  tls:
    termination: reencrypt
    insecureEdgeTerminationPolicy: Redirect
```
I can add via a yaml fragment. However, it would be nice to not having to write any yaml at all :)

version: openshift-maven-plugin:1.0.0-rc-1

Any thoughts on this? It seems like AutoTLS is a bit moot, if the route cannot be secured? Or is there another use case for this?
