### ISSUE TITLE
Allow Eclipse JKube to override default port names

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#367]
### Description

Right now we're building opinionated port names based on protocol and port number. We should provide some way to customize ports to name mapping ~rather than~ in addition to opinionated defaults. Maybe adding another field in DefaultServiceEnricher's Config which should be read before loading default values can solve this.

https://github.com/eclipse/jkube/blob/8ca3f342372128fe12ea1572db1e37d033406a94/jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/DefaultServiceEnricher.java#L488-L500

### Info

* Eclipse JKube version : 1.0.0-rc-1
* Maven version (`mvn -v`) :
```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /opt/apache-maven
Java version: 14.0.1, vendor: Oracle Corporation, runtime: /usr/java/jdk-14.0.1
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.7.11-200.fc32.x86_64", arch: "amd64", family: "unix"
```
* Kubernetes / Red Hat OpenShift setup and version : Affects all versions

* If it's a bug, how to reproduce :

* If it's a feature request, what is your use case :
To be able to customize exposed ports' names.

* Sample Reproducer Project : I realized this issue while migrating https://github.com/IBM/spring-cloud-kubernetes-with-istio to JKube, but it can be reproduced on any project. Port names are always of one of the values in `getDefaultPortName` method

**Comment by manusa** [comment]
Only the port names for the ports you mention in your snippet are taken from opinionated defaults.

The rest of the ports are retrieved by hitting an endpoint from IANA.

**Comment by manusa** [comment]
Not sure if this was adressed on #513 / #519

**Comment by rohanKanojia** [comment]
I think this should be fixed now. I tried with this Service resource fragment:
```yaml
spec:
  type: LoadBalancer
  ports:
    - name: httpnarere
      port: 8240
```
When I ran `mvn k8s:resource` goal I could see that both name and port number are reserved by Eclipse JKube. 
```
eclipse-jkube-sample-with-resource-fragments : $ cat target/classes/META-INF/jkube/kubernetes/external-resources-service.yml 
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /metrics
    jkube.io/git-branch: master
    prometheus.io/port: "9779"
    jkube.io/scm-url: https://github.com/spring-projects/spring-boot/spring-boot-starter-parent/external-resources
    prometheus.io/scrape: "true"
    jkube.io/git-url: git@github.com:r0haaaan/eclipse-jkube-sample-with-resource-fragments.git
    jkube.io/scm-tag: HEAD
    jkube.io/git-commit: 1baf9f6f08ae8a1397a6e00fea62e75bfb659718
  labels:
    app: external-resources
    provider: jkube
    version: 1.4.0-SNAPSHOT
    group: org.eclipse.jkube.quickstarts.maven
  name: external-resources
spec:
  ports:
  - name: httpnarere
    port: 8240
    protocol: TCP
  selector:
    app: external-resources
    provider: jkube
    group: org.eclipse.jkube.quickstarts.maven
  type: LoadBalancer
```
