### ISSUE TITLE
Yaml extract for routes

### ISSUE THREAD

**Issue by jfdenise** [eclipse/jkube#382]
### Description
The goal is to evolve a generated route with support for https. Adding something like to the spec:
```
spec:
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
```
It is not clear on how this should be handled. Currently custom spec element is not merged with the spec element of the generated route, the generated route's spec element is replaced with the content of the extract file. NB: this can be acceptable although the documentation doesn't state how to customize routes.

### Info

* Eclipse JKube version : 1.0.0

* If it's a bug, how to reproduce : add a route.yml extract in the src/jkube directory of a quickstart.
