### ISSUE TITLE
Ingress generations fails, TLS issue?

### ISSUE THREAD

**Issue by semanticfire** [eclipse/jkube#387]
### Description
I cannot get Ingress support working with both the XML method and with the Resource Fragment option

If I use the following fragment (which works on my k8s instance):

```yaml
apiVersion: networking.k8s.io/v1
metadata:
  name: my-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - my.host.com
    secretName: letsencrypt-prod
  rules:
  - host: my.host.com
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: my-service
              port: 
                number: 8080
```
I get the following error:
`Execution default-cli of goal org.eclipse.jkube:kubernetes-maven-plugin:1.0.0:resource failed: No resource type found for:networking.k8s.io/v1#Ingress`
### Info

* Eclipse JKube version : 1.0.0
* Maven version (`mvn -v`) : 3.6.0

* Kubernetes / Red Hat OpenShift setup and version :
Kubernetes 1.19

* If it's a bug, how to reproduce :
add the above fragment in src/main/jkube/ingress.yaml and you'll get the error.

* If it's a feature request, what is your use case :
