### ISSUE TITLE
ISTIO artifact Enrichment

### ISSUE THREAD

**Issue by pmbsa** [eclipse/jkube#427]
### Description
Support ISTIO fragment enrichment or just ISTIO raw resources (raised in fabric8 as well https://github.com/fabric8io/fabric8-maven-plugin/issues/1820)
### Info
Hi, I realise fabric8 is now deprecated, we are planning a migration but that could take some time in the organisation I am working with. I wanted to know if there is a way for me to manage ISTIO resources within a fabric8 project. Even if I cant enrich them during the build I would like to at least be able to apply them so I can keep the delivery mechanisms the same for all projects. I have tried putting the .yml files into a raw folder but I still couldn't get the project to build. Any advice would be much appreciated.

thanks
Paul

* f-m-p version : 4.3.1

**Comment by manusa** [comment]
Hi @pmbsa 
Could you please provide some code, YAML samples, link to other repos, etc. and describe the current behavior vs. the expected behavior? It would really help us get this feature completed faster.

**Comment by pmbsa** [comment]
Ye, Sorry, I made the daft assumption that this was something people were already doing so the ticket was structured more as a query than a request.

Right, examples of the yml for ISTIO artifacts are 
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: minipbin
spec:
  hosts:
  - "mini.example.com"
  gateways:
  - mygateway-https
  http:
  - match:
    - uri:
        prefix: /status
    - uri:
        prefix: /delay
    route:
    - destination:
        port:
          number: 8000
        host: minibin
```
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: mygateway-https
spec:
  selector:
    istio: ingressgateway # use istio default ingress gateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: minibin-credential # must be the same as secret
    hosts:
    - mini.example.com
```
There are of course going to be more than that but as you can see they have an istio api and new "kinds". 
### Current behavior (for fabric8 which is all I have access to right now) 
its worth mentioning that here was no expectation of these working off the bat, I was really just trying to use "raw" to be able to pass this stuff on directly knowing there was no enricher for them. (I did try some of the available istio enrichers but they are all way out of date by now.)
mvn clean install -U fabric8:resource

```
[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:4.3.1:resource (default-cli) on project ISTIOGateway: Execution default-cli of goal io.fabric8:fabric8-maven-plugin:4.3.1:resource failed: No resource type found for:networking.istio.io/v1alpha3#Gateway
```
I have tried without the apiversion as well (knowing the outcome would be the same of course)
```
 Failed to execute goal io.fabric8:fabric8-maven-plugin:4.3.1:resource (default-cli) on project ISTIOGateway: Execution default-cli of goal io.fabric8:fabric8-maven-plugin:4.3.1:resource failed: No resource type found for:v1#Gateway

```
###Expected Behavior
I would like to be able to enrich these types of artifacts if it all possible. Failing that, it would be good to be able to at least pass them straight through untouched.

thanks
Paul
