### ISSUE TITLE
Environment Variable - name: HOSTNAME duplicated

### ISSUE THREAD

**Issue by Christian-dev-ops** [eclipse/jkube#493]
### Description

When using the environment variable define into src/main/jkube/deployment.yml with the definition of volumen mount like:

```yaml
spec:
 template:
   spec:
     volumes:
      - name: mydirectory
        persistentVolumeClaim:
          claimName: mydirectory
     containers:
     - env:
       - name: spring.cloud.config.uri
         value: https://host.com
       - name: spring.cloud.config.enabled
         value: true
       - name: spring.cloud.config.profile
         value: dev
       - name: spring.cloud.config.username
         value: admin
       - name: spring.cloud.config.password
         value: admin
     - volumeMounts:
       - name: mydirectory
         mountPath: /mydirectorypath
```

The result is:

```yaml
spec:
        containers:
        - env:
          - name: spring.cloud.config.uri
            value: https://host.com
          - name: spring.cloud.config.enabled
            value: "true"
          - name: spring.cloud.config.profile
            value: dev
          - name: spring.cloud.config.username
            value: admin
          - name: spring.cloud.config.password
            value: admin
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          **- name: HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name**
          image: myImageReference/backend:0.3.0.1
          imagePullPolicy: IfNotPresent
          name: backend
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          securityContext:
            privileged: false
        **- env:
          - name: HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name**
          volumeMounts:
          - mountPath: /mydirectory
            name: pdfdirectorio
        initContainers:
        - command:
          - chmod
          - "777"
          - /pdfs
          image: busybox
          imagePullPolicy: IfNotPresent
          name: jkube-volume-permission
          volumeMounts:
          - mountPath: /mydirectorypath
            name: mydirectory
        volumes:
        - name: mydirectory
          persistentVolumeClaim:
            claimName: mydirectory
```

### Info

* Eclipse JKube version : 1.0.2
* Maven version (`mvn -v`) : 3.6.3
```

```
* Kubernetes / Red Hat OpenShift setup and version : kubernetes 1.19.4

* If it's a bug, how to reproduce : 

You need use the next command: k8s:resource k8s:deploy

**Comment by rohanKanojia** [comment]
I can reproduce it. Thanks for reporting.

**Comment by rohanKanojia** [comment]
@Christian-dev-ops : On some investigation, it seems like plugin is creating two containers; `HOSTNAME` is not duplicated, rather it's being added for both the enrichers. It's due to two different containers being specified in `deployment.yaml` :
```yaml
spec:
 template:
   spec:
     volumes:
      - name: mydirectory
        persistentVolumeClaim:
          claimName: mydirectory
     containers:
     - env: # container 1
       - name: spring.cloud.config.uri
         value: https://host.com
       - name: spring.cloud.config.enabled
         value: true
       - name: spring.cloud.config.profile
         value: dev
       - name: spring.cloud.config.username
         value: admin
       - name: spring.cloud.config.password
         value: admin
     - volumeMounts: # container 2
       - name: mydirectory
         mountPath: /mydirectorypath
```

When I change your fragment manifest like this, I can see single container being generated (with only one `HOSTNAME` variable):
```yaml
spec:
 template:
   spec:
     volumes:
      - name: mydirectory
        persistentVolumeClaim:
          claimName: mydirectory
     containers:
     - env:
       - name: spring.cloud.config.uri
         value: https://host.com
       - name: spring.cloud.config.enabled
         value: true
       - name: spring.cloud.config.profile
         value: dev
       - name: spring.cloud.config.username
         value: admin
       - name: spring.cloud.config.password
         value: admin
       volumeMounts:
         - name: mydirectory
           mountPath: /mydirectorypath
```
The above modified version generates this `Deployment` manifest:
```bash
eclipse-jkube-sample-with-resource-fragments : $ mvn k8s:resource
[INFO] Scanning for projects...
[INFO] 
[INFO] -------< org.eclipse.jkube.quickstarts.maven:external-resources >-------
[INFO] Building Eclipse JKube :: Quickstarts :: Maven :: External Resources 1.1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- kubernetes-maven-plugin:1.1.0-SNAPSHOT:resource (default-cli) @ external-resources ---
[INFO] k8s: Running generator spring-boot
[INFO] k8s: spring-boot: Using Docker image quay.io/jkube/jkube-java-binary-s2i:0.0.8 as base / builder
[INFO] k8s: Using resource templates from /home/rohaan/work/repos/eclipse-jkube-sample-with-resource-fragments/src/main/jkube
[INFO] k8s: jkube-healthcheck-spring-boot: Adding readiness probe on port 8080, path='/health', scheme='HTTP', with initial delay 10 seconds
[INFO] k8s: jkube-healthcheck-spring-boot: Adding liveness probe on port 8080, path='/health', scheme='HTTP', with initial delay 180 seconds
[INFO] k8s: jkube-revision-history: Adding revision history limit to 2
[INFO] k8s: validating /home/rohaan/work/repos/eclipse-jkube-sample-with-resource-fragments/target/classes/META-INF/jkube/kubernetes/ribbon-serviceaccount.yml resource                                                                                                                           
[INFO] k8s: validating /home/rohaan/work/repos/eclipse-jkube-sample-with-resource-fragments/target/classes/META-INF/jkube/kubernetes/external-resources-service.yml resource                                                                                                                      
[INFO] k8s: validating /home/rohaan/work/repos/eclipse-jkube-sample-with-resource-fragments/target/classes/META-INF/jkube/kubernetes/game-config-env-file-configmap.yml resource                                                                                                                  
[INFO] k8s: validating /home/rohaan/work/repos/eclipse-jkube-sample-with-resource-fragments/target/classes/META-INF/jkube/kubernetes/external-resources-deployment.yml resource                                                                                                                   
[WARNING] k8s: Invalid Resource : /home/rohaan/work/repos/eclipse-jkube-sample-with-resource-fragments/target/classes/META-INF/jkube/kubernetes/external-resources-deployment.yml                                                                                                                 
[message=.spec.template.spec.containers[0].env[0].name: does not match the regex pattern ^[A-Za-z_][A-Za-z0-9_]*$, violation type=pattern]       
[message=.spec.template.spec.containers[0].env[2].name: does not match the regex pattern ^[A-Za-z_][A-Za-z0-9_]*$, violation type=pattern]       
[message=.spec.template.spec.containers[0].env[4].name: does not match the regex pattern ^[A-Za-z_][A-Za-z0-9_]*$, violation type=pattern]       
[message=.spec.template.spec.containers[0].env[3].name: does not match the regex pattern ^[A-Za-z_][A-Za-z0-9_]*$, violation type=pattern]       
[message=.spec.template.spec.containers[0].env[1].name: does not match the regex pattern ^[A-Za-z_][A-Za-z0-9_]*$, violation type=pattern]       
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  5.011 s
[INFO] Finished at: 2020-11-30T22:00:14+05:30
[INFO] ------------------------------------------------------------------------
eclipse-jkube-sample-with-resource-fragments : $ cat /home/rohaan/work/repos/eclipse-jkube-sample-with-resource-fragments/target/classes/META-INF/jkube/kubernetes/external-resources-deployment.yml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    jkube.io/git-url: https://github.com/r0haaaan/eclipse-jkube-sample-with-resource-fragments.git
    jkube.io/git-commit: 362063df5f972046b49a37ebcf36b75f8872916e
    jkube.io/git-branch: master
    jkube.io/scm-url: https://github.com/spring-projects/spring-boot/spring-boot-starter-parent/external-resources
    jkube.io/scm-tag: HEAD
  labels:
    app: external-resources
    provider: jkube
    version: 1.1.0-SNAPSHOT
    group: org.eclipse.jkube.quickstarts.maven
  name: external-resources
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: external-resources
      provider: jkube
      group: org.eclipse.jkube.quickstarts.maven
  template:
    metadata:
      annotations:
        jkube.io/scm-url: https://github.com/spring-projects/spring-boot/spring-boot-starter-parent/external-resources
        jkube.io/git-url: https://github.com/r0haaaan/eclipse-jkube-sample-with-resource-fragments.git
        jkube.io/scm-tag: HEAD
        jkube.io/git-commit: 362063df5f972046b49a37ebcf36b75f8872916e
        jkube.io/git-branch: master
      labels:
        app: external-resources
        provider: jkube
        version: 1.1.0-SNAPSHOT
        group: org.eclipse.jkube.quickstarts.maven
    spec:
      containers:
      - env:
        - name: spring.cloud.config.uri
          value: https://host.com
        - name: spring.cloud.config.enabled
          value: "true"
        - name: spring.cloud.config.profile
          value: dev
        - name: spring.cloud.config.username
          value: admin
        - name: spring.cloud.config.password
          value: admin
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: maven/external-resources:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 180
          successThreshold: 1
        name: spring-boot
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 9779
          name: prometheus
          protocol: TCP
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          successThreshold: 1
        securityContext:
          privileged: false
        volumeMounts:
        - mountPath: /mydirectorypath
          name: mydirectory
      initContainers:
      - command:
        - chmod
        - "777"
        - /mydirectorypath
        image: busybox
        imagePullPolicy: IfNotPresent
        name: jkube-volume-permission
        volumeMounts:
        - mountPath: /mydirectorypath
          name: mydirectory
      volumes:
      - name: mydirectory
        persistentVolumeClaim:
          claimName: mydirectory

```
