### ISSUE TITLE
k8s:helm should not escape curly braces

### ISSUE THREAD

**Issue by algolov** [eclipse/jkube#507]
### Description

Blocked by #802  

There is no way to use [predefined helm values](https://github.com/helm/helm/blob/release-2.0/docs/charts.md#predefined-values).

If I specify these values in yaml fragments, then when generating the helm chart, curly braces are escaped

If I write the following in the yaml fragment:

```yaml
metadata:
  labels:
    app.kubernetes.io/instance: "{{ .Release.Name }}"
```

then in the generated helm chart I will get the following:

```yaml
metadata:
  labels:
    app.kubernetes.io/instance: '{{"{{"}} .Release.Name {{"}}"}}'
```

### Info

* Eclipse JKube version : 1.0.2
* Maven version (`mvn -v`) : 3.6.3
