### ISSUE TITLE
openshift-maven-plugin: service.yml fragment with ports creates service with unnamed port mapping

### ISSUE THREAD

**Issue by robinroos** [eclipse/jkube#513]
### Description

Using openshift-maven-plugin in a Spring Boot app, with the "spring boot" generator.

In the absence of any fragments the project builds and deploys successfully to OpenShift.  Once service is defined, "http" TCP 80 -> 8080

The intention of the fragment is to define an ADDITIONAL service, "hazelcast" TCP 5701 -> 5701.

src/main/jkube/service.yml:
```
spec:
  ports:
    - name: hazelcast
      protocol: TCP
      port: 5701
      targetPort: 5701
```

With the above fragment present, openshift-maven-plugin generates:

target/jkube/applyJson/namespace/service-xxx.json

including the following extract:

```
  "spec" : {
    "clusterIP" : "172.30.157.230",
    "ports" : [ {
      "port" : 5701,
      "protocol" : "TCP",
      "targetPort" : 5701
    } ],
```

Note that the port entry has no name.

At this point deployment is successful; TCP 5701 -> 5701 is exposed by an unnamed port mapping in service-xxx, but there is no HTTP port exposed.

If the fragment is extended to include "http" as follows:

src/main/jkube/service.yml:
```
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: hazelcast
      protocol: TCP
      port: 5701
      targetPort: 5701
```

then openshift-maven-plugin fails (silently) to generate anything in target/jkube/applyJson, possibly due to name collision for two unnamed service port entries, and deployment subsequenly fails with:

```
[ERROR] oc: Failed to update Service from openshift.yml.
```

since openshift.yml is absent.

### Info

```
OpenShift: 4.6
Platform: Windows 10
Eclipse JKube version : 1.0.2

> mvn -v
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: C:\dev\apache-maven-3.6.3\bin\..
Java version: 15.0.1, vendor: AdoptOpenJDK, runtime: C:\Program Files\AdoptOpenJDK\jdk-15.0.1.9-openj9
Default locale: en_GB, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

Potentially relevant maven properties include:

```
<version.jkube>1.0.2</version.jkube>
<maven.compiler.source>11</maven.compiler.source>
<maven.compiler.target>11</maven.compiler.target>
<kubernetes.trust.certificates>true</kubernetes.trust.certificates>
<jkube.enricher.jkube-service.type>ClusterIP</jkube.enricher.jkube-service.type>
<jkube.enricher.jkube-service.normalizePort>true</jkube.enricher.jkube-service.normalizePort>
<jkube.generator.alias>${project.artifactId}</jkube.generator.alias>
```

I will endeavour to add a simple reproducer project as soon as possible.
