### ISSUE TITLE
Upgrade Kubernetes Client to 5.1.1

### ISSUE THREAD

**Issue by apupier** [eclipse/jkube#592]
### Description

currently using 5.0.0 https://github.com/eclipse/jkube/blob/35999caee8736d69a5d3cc6dc6589287e3e7fb3b/jkube-kit/parent/pom.xml#L56

### Info

* Eclipse JKube version :
* Maven version (`mvn -v`) :
```

```
* Kubernetes / Red Hat OpenShift setup and version :

* If it's a bug, how to reproduce :

* If it's a feature request, what is your use case :

* Sample Reproducer Project : *[GitHub Clone URL]*

**Comment by rohanKanojia** [comment]
Hmm, When I testing jkube with `5.1-SNAPSHOT`, I was able to resolve this with these changes:

https://github.com/eclipse/jkube/compare/master...rohanKanojia:pr/upgrade-fabric8-5-1-0?expand=1

Could you please try migrating to `java.util.Base64` and see if it works for you?

**Comment by apupier** [comment]
> Could you please try migrating to `java.util.Base64` and see if it works for you?

it is fixing the compile issue. thanks.

remains a test that is failing https://github.com/eclipse/jkube/pull/593#issue-582161621
```
com.fasterxml.jackson.dataformat.yaml.snakeyaml.error.MarkedYAMLException: while parsing a block mapping
 in 'reader', line 6, column 5:
        app: test
        ^
expected <block end>, but found '<scalar>'
 in 'reader', line 9, column 34:
        helm-variable: "(( required "A valid .Values.global_template_ ... 
                                     ^

 at [Source: (StringReader); line: 9, column: 34]
 ```

**Comment by rohanKanojia** [comment]
ohk, let me try to take a look into it as soon as I finish my current task.

**Comment by apupier** [comment]
I printed the actual and expected content on which it is failing. i tis for the `openshift/templates/test-pod.yaml`

the genrated one contaisn effectively a problem:
```
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: test
    provider: jkube
    version: "1337"
    helm-variable: "{{ required "A valid .Values.global_template_env_var entry required!" .Values.global_template_env_var | default "This is a sample" }}"
  name: test
spec:
  containers:
  - env:
    - name: SAMPLE_ENV_VAR
      value: "${SAMPLE_ENV_VAR}"
    - name: KUBERNETES_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    image: dockerfile/redis
    imagePullPolicy: IfNotPresent
    name: master
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
    - containerPort: 9779
      name: prometheus
      protocol: TCP
    - containerPort: 8778
      name: jolokia
      protocol: TCP
    securityContext:
      privileged: false
```

the line `helm-variable: "{{ required "A valid .Values.global_template_env_var entry required!" .Values.global_template_env_var | default "This is a sample" }}"` is using double-quotes to enclose the value although there are doubcle-quotes inside the value.
