### ISSUE TITLE
Openshift api token via command line for maven build

### ISSUE THREAD

**Issue by ochstobi** [eclipse/jkube#595]
### Info

* Eclipse JKube version : 1.1.1
* Maven version (`mvn -v`) : 3.6.1

Is it possible to provide the Authentication-Token to OpenShift via command line for openshift-maven-plugin? E.g. mvn install -Dtoken=xxx?

**Comment by rohanKanojia** [comment]
Umm, you should be able to deploy to openshift(on 3.x versions) using username and password
```
mvn oc:deploy -Dkubernetes.auth.basic.username=developer -Dkubernetes.auth.basic.password=developer
```

Right now this is not working on OpenShift 4.x versions(see https://github.com/eclipse/jkube/issues/566)

**Comment by ochstobi** [comment]
Thanks for that hint, unfortunately I'm running on OpenShift 4. I have tried to add my credentials to kubeconfig but it doesn't work.
If I add the following to the config file it is working:
```
users:
- name: user/machine
  user:
    token: token
```
But the token expires after one day and I have to refresh it manually. So I tried to add the credentials to the config file like this:
```
users:
- name: user/machine
  user:
    password: password
    username: username
```
But with this configuration the oc:build is breaking with the following error: [ERROR] oc: Failed to execute the build [OpenShift platform has been specified but OpenShift has not been detected!]

Is there a way to add username/password so I don't have to refresh the token every day?
