### ISSUE TITLE
DeploymentConfig for Openshift does not have the correct namespace for the ImageStream

### ISSUE THREAD

**Issue by da-blok** [eclipse/jkube#596]
### Description
When using the openshift version and creating the resources, the openshift-maven-plugin creates the `xxxx-deploymentconfig.yml` which does not use the correct namespace in the image for the container, as well as the namespace configuration under the triggers.

### Info

* Eclipse JKube version : 1.1.1
* Maven version (`mvn -v`) : 3.6.3

### If it's a bug, how to reproduce :
Running `mvn oc:resource` which generates the deployment file under `target/classes/META-INF/jkube/openshift/xxxx-deploymentconfig.yml`

I used `xxxx` for the project artifactId and `yyyy-pu` for the namespace, where the `-pu` stand for the production unit.

#### The output of `oc:resource` look like the following:
[INFO] --- openshift-maven-plugin:1.1.1:resource (default-cli) @ fabric-service ---
[INFO] oc: Using docker image name of namespace: **yyyy-pu**
[INFO] oc: Using resource templates from /Users/.../src/main/jkube
[INFO] oc: jkube-service: Adding a default service 'xxxx' with ports [8080]
[INFO] oc: jkube-service-discovery: Using first mentioned service port '8080'
[INFO] oc: jkube-revision-history: Adding revision history limit to 2
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.104 s
[INFO] Finished at: 2021-03-02T13:14:24+01:00
[INFO] ------------------------------------------------------------------------

After running `oc:resource` without any significant configuration the deployment config looks like this:

```
spec:
  template:
    spec:
      containers:
      - image: yyyy/xxxx:latest
      ...
  triggers:
  - imageChangeParams:
      from:
        kind: ImageStreamTag
        name: xxxx:latest
        namespace: yyyy
```
I'm missing the suffix `-pu` in the namespace and image definition which is required to find the ImageStream in openshift.
