### ISSUE TITLE
Istio VirtualService resource type not found when using helm goal

### ISSUE THREAD

**Issue by jsrolon** [eclipse/jkube#696]
### Description
I can't link to the code directly because it's a private project, but I'm simply trying to add a CustomResource to a Helm chart. Under `src/main/jkube/virtual-service-cr.yml` I have the following:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: project-vs
spec:
  gateways:
  - istio-system/gateway-example-com
  hosts:
  - project.example.com
  http:
  - route:
    - destination:
        host: project
        port:
          number: 8080
```

And I have added the `helm` goal to my executions. The `k8s:resource` goal works well, until it gets to `k8s:helm`:

```
Failed to execute goal org.eclipse.jkube:kubernetes-maven-plugin:1.2.0:helm (default-cli) on project project: Failed to load kubernetes YAML /<project>/target/classes/META-INF/jkube/kubernetes.yml. com.fasterxml.jackson.databind.JsonMappingException: No resource type found for:networking.istio.io/v1alpha3#VirtualService
[ERROR]  at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: io.fabric8.kubernetes.api.model.KubernetesList["items"]->java.util.ArrayList[2])
```

I don't need any enricher support or anything fancy as in #427 . I just need the CustomResource to be added to the Helm chart .tgz.

### Info

* Eclipse JKube version : `1.2.0`
* Maven version (`mvn -v`) : `Apache Maven 3.6.3`
```

```
* Kubernetes / Red Hat OpenShift setup and version : 

```Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.14", GitCommit:"4d62230f10af41cec2851b5b113874f6d2098297", GitTreeState:"clean", BuildDate:"2021-03-22T23:01:55Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
