### ISSUE TITLE
QuarkusHealthCheckEnricher: default health path value is outdated in Quarkus 2.0.0.Final

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#758]
### Description

I was trying out @kameshsampath 's sample when I observed this, somehow pods were not coming in `Ready` state due to probe conditions not getting fulfilled. According to Quarkus docs[0], liveness healthchecks paths are 

```
    /q/health/live - The application is up and running.
    /q/health/ready - The application is ready to serve requests.
    /q/health - Accumulating all health check procedures in the application.
```

However, when running `mvn k8s:resource` liveness/readiness probes are generated with this path:
```yaml
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health/live
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          successThreshold: 1

        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health/ready
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 
```

Looks like behavior in quarkus has changed and `/health/live`, `/health/ready` URLs are no longer supported. I tested with another sample with Quarkus v1.13.7.Final and these were my observations:

v1.13.7.Final
```bash
jkube-quarkus-ingress : $ curl -si localhost:8080/health/ready
HTTP/1.1 301 Moved Permanently
location: /q/health/ready
content-length: 0

jkube-quarkus-ingress : $ curl -si localhost:8080/q/health/ready
HTTP/1.1 200 OK
content-type: application/json; charset=UTF-8
content-length: 46
{
    "status": "UP",
    "checks": [
    ]
}
```

v2.0.0.Final:
```
istio-multi-rev-demo : $ curl -si localhost:8080/health/ready
HTTP/1.1 404 Not Found
Content-Length: 0
Content-Type: application/json

istio-multi-rev-demo : $ curl -si localhost:8080/q/health/ready
HTTP/1.1 200 OK
content-type: application/json; charset=UTF-8
content-length: 46


{
    "status": "UP",
    "checks": [
    ]
}
```

[0] https://quarkus.io/guides/smallrye-health

### Info

* Eclipse JKube version : v1.3.0
* Maven version (`mvn -v`) :
```
Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)
Maven home: /opt/apache-maven
Java version: 11.0.11, vendor: Oracle Corporation, runtime: /usr/java/jdk-11.0.11
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.12.9-300.fc34.x86_64", arch: "amd64", family: "unix"
```
* Kubernetes / Red Hat OpenShift setup and version :

* If it's a bug, how to reproduce : run `mvn k8s:resource` in linked sample

* If it's a feature request, what is your use case : 

* Sample Reproducer Project : https://github.com/kameshsampath/istio-multi-rev-demo
