### ISSUE TITLE
OpenShift Maven Plugin doesn't remove periods from container name.

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#908]
### Description

I noticed this when I was trying to reproduce https://github.com/eclipse/jkube/issues/904. If you go to [quickstarts/maven/quarkus-customized-image](https://github.com/eclipse/jkube/tree/5e8b297a379cbe13745574a34440e3c0bcfa291c/quickstarts/maven/quarkus-customized-image), image name is configured like this:
```xml
      <plugin>
        <groupId>org.eclipse.jkube</groupId>
        <artifactId>openshift-maven-plugin</artifactId>
        <version>${jkube.version}</version>
        <configuration>
          <images>
            <image>
              <name>${project.groupId}/${project.artifactId}</name>
```

If you'll do `oc:resource` you get a warning at validation phase regarding invalid container name:
```
[WARNING] oc: Invalid Resource : /home/rokumar/work/repos/jkube/quickstarts/maven/quarkus-customized-image/target/classes/META-INF/jkube/openshift/quarkus-customized-image-deploymentconfig.yml
[message=.spec.template.spec.containers[0].name: does not match the regex pattern ^[a-z0-9]([-a-z0-9]*[a-z0-9])?$, violation type=pattern]
```
If you go ahead and do `mvn oc:apply`, the process is going to fail and you'll get 422 from Kubernetes API server.

JKube seems to be generating this as container name:
```yaml
          image: org.eclipse.jkube.quickstarts.maven/quarkus-customized-image:latest
          imagePullPolicy: IfNotPresent
          name: org.eclipse.jkube.quickstarts.maven-quarkus-customized-image
```

I tried same project with fabric8 maven plugin v4.4.1 and it seems to be working okay. Fabric8 Maven Plugin seems to be generating this as container name(notice all periods in container name are removed):
```yaml
          image: org.eclipse.jkube.quickstarts.maven/quarkus-customized-image:latest
          imagePullPolicy: IfNotPresent
          name: orgeclipsejkubequickstartsmaven-quarkus-customized-image
```

### Info

* Eclipse JKube version : 1.4.0
